### ISSUE TITLE
Can't use Telephoto lens on Derpfest Android 14 GSI

### ISSUE THREAD

**Issue by Tinnci** [Andrey0800770/samsung_sdm845-kernel#12]
Can't use Telephoto lens on Derpfest Android 14 GSI, is this a kernel issue?
Do you have any successful attempts of using 2x lens?

**Comment by Andrey0800770** [comment]
This is a problem that occurs on all GSI, it is not kernel related, and unfortunately there is nothing I can do.

**Comment by Tinnci** [comment]
> This is a problem that occurs on all GSI, it is not kernel related, and unfortunately there is nothing I can do.

Is this something related to Hal? In vendor? Is this caused by some proprietary driver from Samsung?

Thank you for your kindly response!😘

**Comment by Andrey0800770** [comment]
It's not a vendor or driver error, it's just a GSI recognition issue, you should contact phunsson and open an issue: [link](https://github.com/phhusson/treble_experimentations)

**Comment by Tinnci** [comment]
> It's not a vendor or driver error, it's just a GSI recognition issue, you should contact phunsson and open an issue: [link](https://github.com/phhusson/treble_experimentations)

Thank you for your kind response! I'll close the issue.
